CREATE TABLE rdxuat_db1.rdx_tbl3 (
    accountId                              string,
    bookingDateTime                        timestamp,
    valueDateTime                          timestamp,
    subAccountLevelMaturityDate            timestamp,
    domainCode                             string,
    familyCode                             string,
    subFamilyCode                          string,
    proprietaryBankTransactionCode         string,
    proprietaryBankTransactionDescription  string,
    creditDebitIndicator                   string,
    amount                                 decimal(18,2),
    amountCurrency                         string,
    balance                                decimal(18,2),
    balanceCurrency                        string,
    processingBranchCode                   string,
    processingBranchDescription            string,
    originCode                             string,
    originDescription                      string,
    transactionId                          string,
    transactionRef                         string,
    transactionInformation                 string,
    creditorAccountId                      string,
    creditorAccountName                    string,
    receivingInstitutionCode               string,
    receivingInstitutionName               string,
    debtorAccountId                        string,
    debtorAccountName                      string,
    sendingInstitutionCode                 string,
    sendingInstitutionName                 string,
    merchantName                           string,
    merchantNameEn                         string,
    src_stm_id                             string,
    load_ts                                timestamp,
    data_dt                                date
)
PARTITIONED BY (data_dt)
LOCATION 's3://<DATA_BUCKET>/warehouse/rdxuat_db1/rdx_tbl3/'
TBLPROPERTIES ('table_type' = 'ICEBERG')
